var annotated_dup =
[
    [ "magnumaf", "namespacemagnumaf.html", [
      [ "util", null, [
        [ "pywrap", null, [
          [ "WrappedArray", "structmagnumaf_1_1util_1_1pywrap_1_1WrappedArray.html", "structmagnumaf_1_1util_1_1pywrap_1_1WrappedArray" ]
        ] ],
        [ "CacheManager", "classmagnumaf_1_1util_1_1CacheManager.html", "classmagnumaf_1_1util_1_1CacheManager" ],
        [ "DoubleOrArray", "classmagnumaf_1_1util_1_1DoubleOrArray.html", "classmagnumaf_1_1util_1_1DoubleOrArray" ],
        [ "HostPtrAccessor", "classmagnumaf_1_1util_1_1HostPtrAccessor.html", "classmagnumaf_1_1util_1_1HostPtrAccessor" ],
        [ "HostPtrManipulator", "classmagnumaf_1_1util_1_1HostPtrManipulator.html", "classmagnumaf_1_1util_1_1HostPtrManipulator" ],
        [ "HostRawPtrAccessor", "classmagnumaf_1_1util_1_1HostRawPtrAccessor.html", "classmagnumaf_1_1util_1_1HostRawPtrAccessor" ],
        [ "HostRawPtrManipulator", "classmagnumaf_1_1util_1_1HostRawPtrManipulator.html", "classmagnumaf_1_1util_1_1HostRawPtrManipulator" ],
        [ "UnitVectorOrArray", "structmagnumaf_1_1util_1_1UnitVectorOrArray.html", "structmagnumaf_1_1util_1_1UnitVectorOrArray" ],
        [ "overloaded", "structmagnumaf_1_1util_1_1overloaded.html", null ],
        [ "mk_vis_overload", "structmagnumaf_1_1util_1_1mk__vis__overload.html", null ],
        [ "mk_vis_overload< F0, Frest... >", "structmagnumaf_1_1util_1_1mk__vis__overload_3_01F0_00_01Frest_8_8_8_01_4.html", "structmagnumaf_1_1util_1_1mk__vis__overload_3_01F0_00_01Frest_8_8_8_01_4" ],
        [ "mk_vis_overload< F0 >", "structmagnumaf_1_1util_1_1mk__vis__overload_3_01F0_01_4.html", "structmagnumaf_1_1util_1_1mk__vis__overload_3_01F0_01_4" ]
      ] ],
      [ "AtomTerm", "classmagnumaf_1_1AtomTerm.html", "classmagnumaf_1_1AtomTerm" ],
      [ "AtomisticDipoleDipoleField", "classmagnumaf_1_1AtomisticDipoleDipoleField.html", "classmagnumaf_1_1AtomisticDipoleDipoleField" ],
      [ "AtomisticDmiField", "classmagnumaf_1_1AtomisticDmiField.html", "classmagnumaf_1_1AtomisticDmiField" ],
      [ "AtomisticExchangeField", "classmagnumaf_1_1AtomisticExchangeField.html", "classmagnumaf_1_1AtomisticExchangeField" ],
      [ "AtomisticExternalField", "classmagnumaf_1_1AtomisticExternalField.html", "classmagnumaf_1_1AtomisticExternalField" ],
      [ "AtomisticUniaxialAnisotropyField", "classmagnumaf_1_1AtomisticUniaxialAnisotropyField.html", "classmagnumaf_1_1AtomisticUniaxialAnisotropyField" ],
      [ "FieldTerm", "classmagnumaf_1_1FieldTerm.html", "classmagnumaf_1_1FieldTerm" ],
      [ "BulkDMIExchangeField", "classmagnumaf_1_1BulkDMIExchangeField.html", "classmagnumaf_1_1BulkDMIExchangeField" ],
      [ "CubicAnisotropyField", "classmagnumaf_1_1CubicAnisotropyField.html", "classmagnumaf_1_1CubicAnisotropyField" ],
      [ "DemagField", "classmagnumaf_1_1DemagField.html", "classmagnumaf_1_1DemagField" ],
      [ "DemagFieldPBC", "classmagnumaf_1_1DemagFieldPBC.html", null ],
      [ "DmiField", "classmagnumaf_1_1DmiField.html", "classmagnumaf_1_1DmiField" ],
      [ "ExchangeField", "classmagnumaf_1_1ExchangeField.html", "classmagnumaf_1_1ExchangeField" ],
      [ "ExchangeFieldPBC", "classmagnumaf_1_1ExchangeFieldPBC.html", "classmagnumaf_1_1ExchangeFieldPBC" ],
      [ "ExternalField", "classmagnumaf_1_1ExternalField.html", "classmagnumaf_1_1ExternalField" ],
      [ "MicroTerm", "classmagnumaf_1_1MicroTerm.html", "classmagnumaf_1_1MicroTerm" ],
      [ "RKKYExchangeField", "classmagnumaf_1_1RKKYExchangeField.html", "classmagnumaf_1_1RKKYExchangeField" ],
      [ "SparseExchangeField", "classmagnumaf_1_1SparseExchangeField.html", "classmagnumaf_1_1SparseExchangeField" ],
      [ "SpinTransferTorqueField", "classmagnumaf_1_1SpinTransferTorqueField.html", "classmagnumaf_1_1SpinTransferTorqueField" ],
      [ "UniaxialAnisotropyField", "classmagnumaf_1_1UniaxialAnisotropyField.html", "classmagnumaf_1_1UniaxialAnisotropyField" ],
      [ "NonequiDemagField", "classmagnumaf_1_1NonequiDemagField.html", "classmagnumaf_1_1NonequiDemagField" ],
      [ "NonequiExchangeField", "classmagnumaf_1_1NonequiExchangeField.html", "classmagnumaf_1_1NonequiExchangeField" ],
      [ "NonequiExternalField", "classmagnumaf_1_1NonequiExternalField.html", "classmagnumaf_1_1NonequiExternalField" ],
      [ "NonequiTerm", "classmagnumaf_1_1NonequiTerm.html", "classmagnumaf_1_1NonequiTerm" ],
      [ "NonequiUniaxialAnisotropyField", "classmagnumaf_1_1NonequiUniaxialAnisotropyField.html", "classmagnumaf_1_1NonequiUniaxialAnisotropyField" ],
      [ "AdaptiveRungeKutta", "classmagnumaf_1_1AdaptiveRungeKutta.html", "classmagnumaf_1_1AdaptiveRungeKutta" ],
      [ "Controller", "classmagnumaf_1_1Controller.html", "classmagnumaf_1_1Controller" ],
      [ "movable_il", "structmagnumaf_1_1movable__il.html", "structmagnumaf_1_1movable__il" ],
      [ "LLGIntegrator", "classmagnumaf_1_1LLGIntegrator.html", "classmagnumaf_1_1LLGIntegrator" ],
      [ "Stochastic_Integrator", "classmagnumaf_1_1Stochastic__Integrator.html", "classmagnumaf_1_1Stochastic__Integrator" ],
      [ "Stochastic_LLG", "classmagnumaf_1_1Stochastic__LLG.html", "classmagnumaf_1_1Stochastic__LLG" ],
      [ "Mesh", "structmagnumaf_1_1Mesh.html", "structmagnumaf_1_1Mesh" ],
      [ "NonequiMesh", "structmagnumaf_1_1NonequiMesh.html", "structmagnumaf_1_1NonequiMesh" ],
      [ "CG_Minimizer", "classmagnumaf_1_1CG__Minimizer.html", "classmagnumaf_1_1CG__Minimizer" ],
      [ "LBFGS_Minimizer", "classmagnumaf_1_1LBFGS__Minimizer.html", "classmagnumaf_1_1LBFGS__Minimizer" ],
      [ "Minimizer", "classmagnumaf_1_1Minimizer.html", "classmagnumaf_1_1Minimizer" ],
      [ "StringMethod", "classmagnumaf_1_1StringMethod.html", "classmagnumaf_1_1StringMethod" ],
      [ "State", "classmagnumaf_1_1State.html", "classmagnumaf_1_1State" ],
      [ "ArgParser", "classmagnumaf_1_1ArgParser.html", "classmagnumaf_1_1ArgParser" ],
      [ "GradientDecent", "classmagnumaf_1_1GradientDecent.html", "classmagnumaf_1_1GradientDecent" ],
      [ "NamedType", "classmagnumaf_1_1NamedType.html", "classmagnumaf_1_1NamedType" ],
      [ "NewtonIteration", "classmagnumaf_1_1NewtonIteration.html", "classmagnumaf_1_1NewtonIteration" ],
      [ "StageTimer", "classmagnumaf_1_1StageTimer.html", "classmagnumaf_1_1StageTimer" ],
      [ "Version", "structmagnumaf_1_1Version.html", "structmagnumaf_1_1Version" ],
      [ "ZeroCrossing", "classmagnumaf_1_1ZeroCrossing.html", "classmagnumaf_1_1ZeroCrossing" ]
    ] ],
    [ "magnumafpy", "namespacemagnumafpy.html", [
      [ "Conversion", "classmagnumafpy_1_1Conversion.html", null ],
      [ "Util", "classmagnumafpy_1_1Util.html", null ],
      [ "Geometry", "classmagnumafpy_1_1Geometry.html", null ],
      [ "Magnetization", "classmagnumafpy_1_1Magnetization.html", null ],
      [ "Field", "classmagnumafpy_1_1Field.html", null ],
      [ "dictproperty", "classmagnumafpy_1_1dictproperty.html", "classmagnumafpy_1_1dictproperty" ],
      [ "Mesh", "classmagnumafpy_1_1Mesh.html", "classmagnumafpy_1_1Mesh" ],
      [ "NonequiMesh", "classmagnumafpy_1_1NonequiMesh.html", "classmagnumafpy_1_1NonequiMesh" ],
      [ "State", "classmagnumafpy_1_1State.html", "classmagnumafpy_1_1State" ],
      [ "Stochastic_LLG", "classmagnumafpy_1_1Stochastic__LLG.html", "classmagnumafpy_1_1Stochastic__LLG" ],
      [ "LLGIntegrator", "classmagnumafpy_1_1LLGIntegrator.html", "classmagnumafpy_1_1LLGIntegrator" ],
      [ "StringMethod", "classmagnumafpy_1_1StringMethod.html", "classmagnumafpy_1_1StringMethod" ],
      [ "HeffTerm", "classmagnumafpy_1_1HeffTerm.html", "classmagnumafpy_1_1HeffTerm" ],
      [ "DemagField", "classmagnumafpy_1_1DemagField.html", "classmagnumafpy_1_1DemagField" ],
      [ "DemagFieldPBC", "classmagnumafpy_1_1DemagFieldPBC.html", "classmagnumafpy_1_1DemagFieldPBC" ],
      [ "ExchangeField", "classmagnumafpy_1_1ExchangeField.html", "classmagnumafpy_1_1ExchangeField" ],
      [ "SparseExchangeField", "classmagnumafpy_1_1SparseExchangeField.html", "classmagnumafpy_1_1SparseExchangeField" ],
      [ "ExchangeFieldPBC", "classmagnumafpy_1_1ExchangeFieldPBC.html", "classmagnumafpy_1_1ExchangeFieldPBC" ],
      [ "BulkDMIExchangeField", "classmagnumafpy_1_1BulkDMIExchangeField.html", "classmagnumafpy_1_1BulkDMIExchangeField" ],
      [ "DmiField", "classmagnumafpy_1_1DmiField.html", "classmagnumafpy_1_1DmiField" ],
      [ "NonequiDemagField", "classmagnumafpy_1_1NonequiDemagField.html", "classmagnumafpy_1_1NonequiDemagField" ],
      [ "NonequiExternalField", "classmagnumafpy_1_1NonequiExternalField.html", "classmagnumafpy_1_1NonequiExternalField" ],
      [ "NonequiExchangeField", "classmagnumafpy_1_1NonequiExchangeField.html", "classmagnumafpy_1_1NonequiExchangeField" ],
      [ "CubicAnisotropyField", "classmagnumafpy_1_1CubicAnisotropyField.html", "classmagnumafpy_1_1CubicAnisotropyField" ],
      [ "UniaxialAnisotropyField", "classmagnumafpy_1_1UniaxialAnisotropyField.html", "classmagnumafpy_1_1UniaxialAnisotropyField" ],
      [ "NonequiUniaxialAnisotropyField", "classmagnumafpy_1_1NonequiUniaxialAnisotropyField.html", "classmagnumafpy_1_1NonequiUniaxialAnisotropyField" ],
      [ "AtomisticDipoleDipoleField", "classmagnumafpy_1_1AtomisticDipoleDipoleField.html", "classmagnumafpy_1_1AtomisticDipoleDipoleField" ],
      [ "AtomisticUniaxialAnisotropyField", "classmagnumafpy_1_1AtomisticUniaxialAnisotropyField.html", "classmagnumafpy_1_1AtomisticUniaxialAnisotropyField" ],
      [ "AtomisticExchangeField", "classmagnumafpy_1_1AtomisticExchangeField.html", "classmagnumafpy_1_1AtomisticExchangeField" ],
      [ "AtomisticDmiField", "classmagnumafpy_1_1AtomisticDmiField.html", "classmagnumafpy_1_1AtomisticDmiField" ],
      [ "ExternalField", "classmagnumafpy_1_1ExternalField.html", "classmagnumafpy_1_1ExternalField" ],
      [ "AtomisticExternalField", "classmagnumafpy_1_1AtomisticExternalField.html", "classmagnumafpy_1_1AtomisticExternalField" ],
      [ "SpinTransferTorqueField", "classmagnumafpy_1_1SpinTransferTorqueField.html", "classmagnumafpy_1_1SpinTransferTorqueField" ],
      [ "RKKYExchangeField", "classmagnumafpy_1_1RKKYExchangeField.html", "classmagnumafpy_1_1RKKYExchangeField" ],
      [ "LBFGS_Minimizer", "classmagnumafpy_1_1LBFGS__Minimizer.html", "classmagnumafpy_1_1LBFGS__Minimizer" ],
      [ "Constants", "classmagnumafpy_1_1Constants.html", null ]
    ] ]
];